name: 'Parse Backport Comments'
description: 'Parses backport branches from backport comments tagged with [backport].'
inputs:
  pr_number:
    description: "The number of the PR to check for backporting."
    required: true
    # type: number
  token:
    description: "The GitHub token to use for API calls."
    default: ${{ github.token }}
outputs:
  backport_branches:
    description: "Backport branches parsed from comments."
runs:
  using: 'node24'
  main: 'index.js'
